#!/usr/bin/env pwsh
# Deploy Function App Code
# This script is auto-generated by Terraform

Write-Host "Deploying Function App code..." -ForegroundColor Cyan

$resourceGroup = "function-monitor-rg-wwlkqk"
$functionAppName = "function-monitor-func-wwlkqk"
$zipFile = "function-app.zip"

Write-Host "Resource Group: $resourceGroup" -ForegroundColor Yellow
Write-Host "Function App: $functionAppName" -ForegroundColor Yellow
Write-Host "Zip File: $zipFile" -ForegroundColor Yellow

# Check if zip file exists
if (-not (Test-Path $zipFile)) {
    Write-Host "Error: $zipFile not found!" -ForegroundColor Red
    exit 1
}

# Deploy the function app
Write-Host "`nDeploying to Azure..." -ForegroundColor Green
az functionapp deployment source config-zip `
    --resource-group $resourceGroup `
    --name $functionAppName `
    --src $zipFile

if ($LASTEXITCODE -eq 0) {
    Write-Host "`nDeployment successful!" -ForegroundColor Green
    Write-Host "Function App URL: https://function-monitor-func-wwlkqk.azurewebsites.net" -ForegroundColor Cyan
    Write-Host "HTTP Trigger URL: https://function-monitor-func-wwlkqk.azurewebsites.net/api/HttpTrigger1" -ForegroundColor Cyan
} else {
    Write-Host "`nDeployment failed!" -ForegroundColor Red
    exit 1
}
